### PR TITLE
Update readme and made licensing more visible to github standards

### PR DESCRIPTION
**Pull request by christianneu**
- Updated license information to show in repository overview on GitHub
- Updated README.md with more information and especially license information as they should be directly visible
- Added CONTRIBUTING.md
- Added CODE_OF_CONDUCT.md

I am not aware who is actually the owner of this repository so I took the information from the dgc-business-rules repository. Please correct me if I am wrong about this.

### CODE REVIEW

**Comment by daniel-eder** [comment]
@christianneu First off, thank you for helping to create a clear picture of the license situation for all project participants.

You couldn't know this (and I'll comment on the business rules repo as well), but the code of conduct and contribution instructions are not ideal for repositories of the eHN. We use them in the Telekom repositories in the https://github.com/eu-digital-green-certificates organization, because we have community managers to enforce this code, and a legal entity to take responsibility for such choices. They are, however, not an ideal choice for the eHN. 

May I ask you to update and simplify the PR in the following way (any eHN Members: Please correct me if you have different requirements):

- Remove CODE_OF_CONDUCT
- Remove CONTRIBUTING
- Remove the T-Systems Copyright from the readme - we did not create this piece of software. An appropriate attribution would be the authors present in the source code files, or possibly `Copyright (C) 2021 eHealth Network and all other contributors`, although I am not sure if the eHN is a legal entity. 

@dirkx can you weigh in on your preferences regarding the Copyright?

**Comment by dirkx** [comment]
Copyright can be changed to something like 'the eHealth implementors group" or "eHealth Implementors"

**Comment by christianneu** [comment]
Thanks for your update.

I've updated the pull request in regard to the comments of you and Daniel.

Could you please merge the PR into main now?

**Comment by daniel-eder** [comment]
@dirkx may I ask you to review?

**Pull request merged**
